In [2]:
import numpy as np

In [14]:
a1=[1,2,3,4,5,6,7,8,9]

In [15]:
print(a1)
print(type(a1))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [16]:
print(np.array(a1))

[1 2 3 4 5 6 7 8 9]


In [17]:
a2=np.array(a1)

In [18]:
print(a2)
print(type(a2))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [20]:
a3=np.zeros(10)
print(a3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
a3=np.ones((2,3))
print(a3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
a4=np.eye(5)
a4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
a5=np.identity(5)
a5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a6=np.empty((3,4))
a6

array([[4.45057637e-308, 1.78021527e-306, 8.45549797e-307,
        1.37962049e-306],
       [1.11260619e-306, 1.78010255e-306, 9.79054228e-307,
        4.45057637e-308],
       [8.45596650e-307, 9.34602321e-307, 4.94065646e-322,
        0.00000000e+000]])

In [3]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [4]:

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
# Get Dimension
a.ndim

1

In [6]:

# Get Shape
b.shape

(2, 3)

In [7]:
# Get Type
a.dtype

dtype('int32')

In [8]:
# Get Size
a.itemsize

4

In [9]:
# Get number of elements
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1, 5]

13

In [12]:

# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [15]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [17]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
# replace 
b[:,1,:] = [[0,0],[8,8]]

In [26]:
b

array([[[1, 2],
        [0, 0]],

       [[5, 6],
        [8, 8]]])

# Initializing Different Types of Arrays

In [27]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [29]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [30]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [31]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.92495291, 0.02001933],
       [0.36576478, 0.91909034],
       [0.7300892 , 0.93411106],
       [0.6611467 , 0.58796187]])

In [32]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 0,  5,  6],
       [ 7,  3, -4],
       [ 0, -1,  0]])

In [33]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [35]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays!!!

In [36]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics

In [37]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [38]:
a+2

array([3, 4, 5, 6])

In [39]:
a-2

array([-1,  0,  1,  2])

In [40]:
a*2

array([2, 4, 6, 8])

In [41]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [42]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [43]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [44]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [45]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [46]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [47]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

## Statistics

In [48]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.min(stats)

1

In [50]:
np.max(stats, axis=1)

array([3, 6])

In [51]:
np.min(stats,axis=1)

array([1, 4])

In [52]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [56]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print("Before")
print(before)
print("After")
after = before.reshape((4,2))
print(after)

Before
[[1 2 3 4]
 [5 6 7 8]]
After
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [57]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load Data from File

In [61]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5
   3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12
   1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]


### Boolean Masking and Advanced Indexing

In [62]:
(~((filedata > 50) & (filedata < 100)))

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False, False])